before_install:
  - rm -f Gemfile.lock

rvm:
  - 2.0.0

env:
  - PUPPET_VERSION="~> 3.7.0"
  - PUPPET_VERSION="~> 3.6.0"
  - PUPPET_VERSION="~> 3.5.0"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.3.0"
  - PUPPET_VERSION="~> 3.2.0"
